# Default values for sigscale-cse
#
replicaCount: 1
image:
  repository: sigscale/cse
  pullPolicy: IfNotPresent
  tag: ""
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""
podAnnotations: {}
podLabels: {}
restService:
  type: LoadBalancer
  clusterIP: ""
  port: 80
m3uaService:
  create: false
  type: ClusterIP
  clusterIP: ""
  port: 2905
diameterAcctService:
  create: false
  type: ClusterIP
  clusterIP: ""
  protocol: TCP
  port: 3868
diameterAuthService:
  create: false
  type: ClusterIP
  clusterIP: ""
  protocol: TCP
  port: 3869
snmpService:
  create: false
  type: ClusterIP
  clusterIP: ""
  port: 4161
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
podResources: {}
nodeSelector: {}
tolerations: []
affinity: {}
dataVolume:
  size: 10Gi
  class: ""
logsVolume:
  size: 10Gi
  class: ""
erlangArgs: ""
cseConfig:
  create: false
  sysConfig: "[]."
