{{- if .Values.cseConfig.create -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-cse-config
  labels:
    {{- include "sigscale-cse.labels" . | nindent 4 }}
data:
  sys.config: {{ .Values.cseConfig.sysConfig | quote }} 
{{- end }}
