{{- if .Values.diameterAuthService.create -}}
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-diameter-auth
  labels:
    {{- include "sigscale-cse.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "sigscale-cse.selectorLabels" . | nindent 6 }}
  type: {{ .Values.diameterAuthService.type }}
  ports:
  - protocol: TCP
    appProtocol: diameter
    {{- if .Values.diameterAuthService.clusterIP }}
    clusterIP: {{ .Values.diameterAuthService.clusterIP }}
    {{- end }}
    port: {{ .Values.diameterAuthService.port }}
    targetPort: diameter-auth
{{- end }}
