{{- if .Values.m3uaService.create -}}
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-diameter-acct
  labels:
    {{- include "sigscale-cse.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "sigscale-cse.selectorLabels" . | nindent 6 }}
  type: {{ .Values.m3uaService.type }}
  ports:
  - protocol: {{ .Values.m3uaService.protocol }}
    appProtocol: m3ua
    port: {{ .Values.m3uaService.port }}
    targetPort: m3ua
{{- end }}
