{{- if .Values.m3uaService.create -}}
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-m3ua
  labels:
    {{- include "sigscale-cse.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "sigscale-cse.selectorLabels" . | nindent 6 }}
  type: {{ .Values.m3uaService.type }}
  ports:
  - protocol: SCTP
    appProtocol: m3ua
    {{- if .Values.m3uaService.clusterIP }}
    clusterIP: {{ .Values.m3uaService.clusterIP }}
    {{- end }}
    port: {{ .Values.m3uaService.port }}
    targetPort: m3ua
{{- end }}
