{{- if .Values.radiusAuthService.create -}}
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-radius-auth
  labels:
    {{- include "sigscale-cse.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "sigscale-cse.selectorLabels" . | nindent 6 }}
  type: {{ .Values.radiusAuthService.type }}
  ports:
  - protocol: UDP
    appProtocol: radius
    {{- if .Values.radiusAuthService.clusterIP }}
    clusterIP: {{ .Values.radiusAuthService.clusterIP }}
    {{- end }}
    port: {{ .Values.radiusAuthService.port }}
    targetPort: radius-auth
{{- end }}
