{{- if .Values.restService.create -}}
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-cse-rest
  labels:
    {{- include "sigscale-cse.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "sigscale-cse.selectorLabels" . | nindent 6 }}
  type: {{ .Values.restService.type }}
  ports:
  - protocol: TCP
    appProtocol: http
    port: {{ .Values.restService.port }}
    targetPort: rest
{{- end }}
