{{- if .Values.snmpService.create -}}
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-cse-snmp
  labels:
    {{- include "sigscale-cse.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "sigscale-cse.selectorLabels" . | nindent 6 }}
  type: {{ .Values.snmpService.type }}
  ports:
  - protocol: UDP
    appProtocol: snmp
    {{- if .Values.snmpService.clusterIP }}
    clusterIP: {{ .Values.snmpService.clusterIP }}
    {{- end }}
    port: {{ .Values.snmpService.port }}
    targetPort: snmp
{{- end }}
